name: crypto_tracker
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^1.1.0
  flutter_redux: 0.7.0
  redux: ^4.0.0+2
  redux_thunk: ^0.3.0
  http: ^0.12.2
  json_annotation: ^3.0.0
  dropdown_search: 0.4.8
  flutter_spinkit: ^4.1.2
  enum_to_string: ^1.0.14
  flutter_svg: ^0.19.2+1
  intl: ^0.16.1
  trading_chart: ^0.1.2
  shared_preferences: ^2.0.5
  smart_select: ^4.3.2
#  aws_sns_api: ^0.2.0
  amplify_flutter: ^0.1.1
  amplify_auth_cognito: ^0.1.1
  amplify_api: ^0.1.1
  cupertino_icons: ^0.1.3
  provider: any
  flutter_local_notifications: ^5.0.0+1
  rxdart: ^0.26.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.2.0

flutter:
  uses-material-design: true
  assets:
     - assets/bot.svg
     - assets/bitcoin.svg
     - assets/background.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
